###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: '3.1'
services:
    mariadb:
        image: 'mariadb:11.0'
        working_dir: /application
        volumes:
            - '.:/application'
        environment:
            - MYSQL_ROOT_PASSWORD=cortex
            - MYSQL_DATABASE=db
            - MYSQL_USER=cortex
            - MYSQL_PASSWORD=cortex
        ports:
            - '41003:3306'

    webserver:
        image: 'nginx:alpine'
        working_dir: /application
        volumes:
            - '.:/application'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '41000:80'

    php-fpm:
        build: phpdocker/php-fpm
        working_dir: /application
        volumes:
            - '.:/application'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.4/fpm/conf.d/99-overrides.ini'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.4/cli/conf.d/99-overrides.ini'

    # If we were starting from scratch we wouldn't need this until we create the demo directory
        command: >
            /bin/sh -c "
            chown -R www-data:www-data /application/demo/www /application/demo/log /application/demo/temp &&
            chmod -R 777 /application/demo/log /application/demo/temp &&
            chmod -R 755 /application/demo/www &&
            php-fpm8.4"